apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-notes-deployment
  namespace: next-notes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: next-notes
  template:
    metadata:
      labels:
        app: next-notes
    spec:
      containers:
        - name: next-notes
          image: ghcr.io/kkrish-77/next.js-minikube-deployment:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
